### PR TITLE
`Hub` is dead. Long live `gh`

### LINKED ISSUE #14: `Hub` is dead. Long live `gh`
The `hub` CLI was not updated [since March 2020](https://github.com/github/hub/tags).
It does not seem that `hub` will be updated (see [this issue](https://github.com/github/hub/issues/2470)).

There is an official `gh` [CLI tool from GitHub](https://cli.github.com/). Let's use it.

### PR DESCRIPTION
**Pull request by Adeynack**
fixes #14

### CODE REVIEW

**Review by JensRavens — APPROVED** [review]

**Comment by Adeynack** [comment]
@JensRavens What action do we need to perform to have it appear [on Ruby Gem](https://rubygems.org/gems/pull-request)?

**Comment by JensRavens** [comment]
Happens by creating a release via the github UI (there's an action that pushes it to rubygems). Already published as version 0.5.

**Comment by Adeynack** [comment]
@JensRavens Why is it then showing that nothing was ever published?

image

**Comment by Adeynack** [comment]
OK I guess I found it in [_Actions_](https://github.com/nerdgeschoss/pull-request/actions).

- Why is there 2 of them?
- Why is one red?

**Comment by JensRavens** [comment]
It's red because it was the first run (when I pushed the action). The actual run was green.
Also this is not about packages (we're not using the github package registry) but about releases:
Screenshot 2022-11-10 at 14 12 54

**Comment by JensRavens** [comment]
on the release page:
Screenshot 2022-11-15 at 16 08 35
Screenshot 2022-11-15 at 16 08 51
Screenshot 2022-11-15 at 16 09 07

**Pull request merged**
